### ISSUE TITLE
Proposed usage is not compatible with ts 3.1.3.

### ISSUE THREAD

**Issue by kamilogerto2** [cartant/ts-action-operators#10]
After upgrade project to Angular 7 (ts 3.1.3) usage like this:
`ofType(action),`
is not compatible.

Now we need to add T definition like:
`ofType<ActionCtor>(action),`
I supposed that "T extends string" has different meaning in new ts.

**Comment by cartant** [comment]
As noted in the `ts-action` issue that you opened, the tests pass with the latest version of TypeScript - [3.1.4](https://github.com/cartant/ts-action-operators/blob/master/yarn.lock#L1302-L1304). So this needs more information. See also: https://itnext.io/how-to-write-a-bug-report-3333d8e41efb

Not trying to be snarky with that link, but bug reports need more information than you've provided.

**Comment by kamilogerto2** [comment]
Easy ;) You are right. I left you comment in ts-action. Thank you for this libraries! ;)
