### ISSUE TITLE
how to use this library with ngrx effects ?

### ISSUE THREAD

**Issue by cvgaviao** [cartant/ts-action-operators#3]
it is not clear in the doc available how to use ofType() and toPayload() methods with standard ngrx effects classes.
In the docs there is this example: 
```javascript
actions
  .ofType(Books.Search)
  .toPayload()
```

but how is 'actions' observable defined?

in standard effect classes we inject actions from `@ngrx/effects` in the constructor.

```javascript
import { Effect, Actions } from '@ngrx/effects';

constructor(
    private actions$: Actions
  ) {}
```
But I was not able to use toPayload() since it isn't part of Actions:

```javascript
@Effect() fooAction$ = this.actions$
  .ofType(Foo)
  .toPayload()
  .switchMap(payload => ...);
```

**Comment by cartant** [comment]
Okay, I see the problem.

These days I use pipeable operators, so I didn't give sufficient thought to that patching `ofType` into `Observable.protoype` and didn't realise that doing so wouldn't yield the expected result.

The examples using pipe will work, but the in the prototype-patching example, you can use `let` instead, like this:

```ts
import { ofType, toPayload } from "ts-action-operators";
@Effect() fooAction$ = this.actions$
  .let(ofType(Foo))
  .let(toPayload())
  .switchMap(payload => ...);
```

The NgRx `Actions` observable implements its own `ofType` method and that replaces the method patched into `Observable.prototype`.

**Comment by cartant** [comment]
I've removed the prototype patching entirely. You'll need to use:

```ts
import { ofType, toPayload } from "ts-action-operators";
@Effect() fooAction$ = this.actions$
  .let(ofType(Foo))
  .let(toPayload())
  .switchMap(payload => ...);
```
or
```ts
import { ofType, toPayload } from "ts-action-operators";
@Effect() fooAction$ = this.actions$
  .pipe(ofType(Foo), toPayload())
  .switchMap(payload => ...);
```
or switch to using only pipeable operators (which I'd recommend).

**Comment by cartant** [comment]
Thanks for raising the issue.

**Comment by cvgaviao** [comment]
Now I'm aware of what pipeable operators is and I will use them...
Thanks !
